version: '3.8'

services:
  mind_database_prod_host:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env.prod
    volumes:
      - mind_database_prod_volume:/var/lib/postgresql/data
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    networks:
      - mind_network_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nestjs:
    build:
      context: .
      target: production
    container_name: nestjs_app_prod
    restart: unless-stopped
    env_file:
      - .env.prod
    ports:
      - "${HOST_API_PORT}:${CONTAINER_API_PORT}"
    depends_on:
      mind_database_prod_host:
        condition: service_healthy
    networks:
      - mind_network_prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mind_database_prod_volume:

networks:
  mind_network_prod:
    driver: bridge
